---
name: "MyShows"
guid: "ef35f6b1-7fe6-44ca-a215-232089fb9bc7"
version: "5.1.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Scrobble your watched shows with MyShows.me"
description: >
  Scrobble your watched shows with MyShows.me.
category: "General"
owner: "shemanaev"
artifacts:
  - "MyShows.dll"
changelog: >
  Update for 10.9 compatibility
