---
name: "jellyfin-plugin-myshows"
guid: "ef35f6b1-7fe6-44ca-a215-232089fb9bc7"
version: "1.0.0"
jellyfin_version: "10.4.0"
nicename: "MyShows"
description: "Scrobble your watched shows with MyShows.me"
overview: >
  Scrobble your watched shows with MyShows.me.
category: "General"
owner: "shemanaev"
artifacts:
  - "MyShows.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
